import { Career } from "@/components/Career";
import { Container } from "@/components/Container";
import { Hero } from "@/components/Hero";
import { Navbar } from "@/components/Navbar";
import { SideProjects } from "@/components/SideProjects";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-full bg-slate-900 text-slate-300 pb-8">
        <div id="background" className=" mb-16">
          <Container>
            <Navbar />
            <Hero />
          </Container>
        </div>
        <Container>
          <SideProjects />
          <div className="h-20" />
          <Career />
        </Container>
      </main>
    </>
  );
}
